### ISSUE TITLE
Cannot set custom thumb XML drawable

### ISSUE THREAD

**Issue by SebSob** [syedowaisali/crystal-range-seekbar#79] opened 2018-01-12 13:09 UTC
**Type**:
CrystalRangeSeekbar

**Problem**
Can't set a custom .xml thumb drawable. (Problem for both XML as Java)

**Code**
```
rangeSeekBar = findViewById(R.id.rangeSeekBar);
rangeSeekBar.setLeftThumbDrawable(R.drawable.custom_rangeseekbar_thumb);
```

**Error log**
`Caused by: java.lang.ClassCastException: android.graphics.drawable.LayerDrawable cannot be cast to android.graphics.drawable.BitmapDrawable
                      at com.crystal.crystalrangeseekbar.widgets.CrystalRangeSeekbar.getBitmap(CrystalRangeSeekbar.java:485)`

 Any idea?

**Comment by mxl** [comment] 2018-01-20 11:27
Duplicate of #14

**Comment by syedowaisali** [comment] 2018-02-02 05:52
XML drawable not supported yet

**Closed by syedowaisali** 2018-02-02 05:52 UTC
